# Generated by Django 6.0.3 on 2026-03-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
    ]
